version: '3.9'

services: 
# postgres
  database:
    container_name: database
    build: .
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./queries/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

volumes:
#postgres
  pgdata:
    